### ISSUE TITLE
Crash exit code 1

### ISSUE THREAD

**Issue by SakkiYasumin** [Luke100000/minecraft-comes-alive#408]
(Version 1.17.1 using forge) 
 My minecraft has been opening fine with some mods but when I added mcar (1.17.1) it started giving me a crash code (exit code 1) right after pressing play on the launcher. I removed all the mods except this one and I tried having only this one + archetectury. I tried with all the mcar version from cursed forge but no luck.

 It gives me no crash report files but here is the latest.log:

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9610057/latest.log)

 And here is the debug log:

[debug.log](https://github.com/Luke100000/minecraft-comes-alive/files/9610051/debug.log)

 Would really appreciate the help! Thank you for reading ^^

**Comment by Luke100000** [comment]
Sadly, I can't spot any errors. You are not the first one with this error, it spans over every MC version and all logs end without any errors at the same moment.

You could check out the `launcher_log.txt` log if it mentions anything else.

**Comment by SakkiYasumin** [comment]
Unfortunately I'm not sure how to read this :') From my understanding it's something to do with the game or java version not being compatible? But it works for everyone else so I don't understand why it doesn't for me. Here's the launcher log:

[launcher_log.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9619950/launcher_log.txt)

Also thank you for the quick reply!

**Comment by Luke100000** [comment]
I think you provided us with a good hint. If you know how, you can specify your own Java 17+ runtime, or you wait until we fixed that.

**Comment by SakkiYasumin** [comment]
I searched and I can't make a thing out of what I need to do, so I can wait for the fix then, it's no problem!
 Thank you for helping me and good luck! I'll stay tuned on curse forge for the update, keep up the good work ^^

**Comment by LegaLT7** [comment]
Did you find a solution? I have the same problem but with 1.18.2 Forge, all my mods work normal but when I use MCA it always crashes when I press the play button. I even tried to reinstall everything from scratch and include only the MCA but the same thing still happens.

**Comment by SakkiYasumin** [comment]
Sadly I didn't, tried in 1.19.2 also didn't work. I'm pretty sure the programmer is already trying to fix it as mentioned above, at least hopefully they're onto something. Not sure what's causing the trouble tho.

**Comment by nindoga** [comment]
Que lástima, estoy igual que vosotros en la versión 1.18.2 y me pasa lo mismo, el error 1... he probado de todo y no deja, espero que lo podáis solucionar, es un mod muy interesante y entretenido! Podríais avisar de alguna manera cuando este error esté arreglado o se pueda saber como solucionar el error? Gracias!!

**Comment by Luke100000** [comment]
Closed, no clues on where to look and if it is a dependency related issue things probably have changed in the past months anyways
